name: Build APK

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_ROOT: ${{ github.workspace }}/android-ndk
      QNN_SDK_ROOT: ${{ github.workspace }}/qnn-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "hello"
